-- CreateTable
CREATE TABLE "public"."leads" (
    "id" SERIAL NOT NULL,
    "first_name" TEXT,
    "last_name" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "postal_code" TEXT,
    "bcbs_type" TEXT,
    "bcbs" TEXT,
    "dentures" TEXT,
    "current_conditions" TEXT,
    "existing_fractured_teeth" TEXT,
    "employer_insurance" TEXT,
    "employer_bcbs_cash" TEXT,
    "how_soon" TEXT,
    "not_ppo_cash_pay" TEXT,
    "pain_discomfort" TEXT,
    "condition_description" TEXT,
    "employer" TEXT,
    "credit_score" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "transcript" TEXT,
    "numberOfMissingTeeth" INTEGER,
    "isDecayedOrRotTeethPresent" BOOLEAN,
    "isUserApplicableForBcbsPpoInsurance" BOOLEAN,
    "isUserUploadingCards" BOOLEAN,
    "isManualConsultationRequired" BOOLEAN,
    "isInsuranceCardValid" BOOLEAN,
    "userInsuranceCard" TEXT,
    "isUserInterestedInCashOptions" BOOLEAN,
    "okayWithPrice" BOOLEAN,
    "preferredTime" TEXT,
    "preferredDay" TEXT,
    "humanInterventionNeeded" BOOLEAN,

    CONSTRAINT "leads_pkey" PRIMARY KEY ("id")
);
